Spring:
  datasource:
    url:
    driverClassName:
    configuration:
      maximum-pool-size: 50
      connection-test-query: SELECT 1


  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.SQLServerDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          batch_size: 4
          order_inserts: true

