Spring:
  datasource:
    url: jdbc:sqlserver://madhura453.database.windows.net:1433;database=madhura453;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;Authentication=ActiveDirectoryIntegrated
    configuration:
      maximum-pool-size: 50
      connection-test-query: SELECT 1
      hikari:
        data-source-properties:
          useUnicode: true
          characterEncoding: UTF-8
      initialize: false


  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.SQLServerDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          batch_size: 4
          order_inserts: true

